server:
  port: 80
  servlet:
    context-path: "/"
spring:
  application:
    name: "client"
  security:
    oauth2:
      client:
        registration:
          gcs_code:
            provider: gcs_code
            client-id: gift-certificates-system-id-code
            client-secret: gift-certificates-system-secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gcs_code"
            scope: module_04::create, module_04::read, module_04::update, module_04::delete
            client-name: Gift-certificates System (Authorization Code Grant)
          gcs_ropc:
            provider: gcs_ropc
            client-id: gift-certificates-system-id-rops
            client-secret: gift-certificates-system-secret
            client-authentication-method: basic
            authorization-grant-type: password
            redirect-uri: "{baseUrl}/login/oauth2/code/gcs_ropc"
            scope: module_04::create, module_04::read, module_04::update, module_04::delete
            client-name: Gift-certificates System (Resouce Owner Password Credentials Grant)
        provider:
          gcs_code:
            authorization-uri: http://localhost:9999/oauth/authorize
            token-uri: http://localhost:9999/oauth/token
            user-info-uri: http://localhost:9999/oauth/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json
          gcs_ropc:
            authorization-uri: http://localhost:9999/oauth/authorize
            token-uri: http://localhost:9999/oauth/token
            user-info-uri: http://localhost:9999/oauth/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"