server:
  port: 80
  servlet:
    context-path: "/"
spring:
  application:
    name: "client"
  security:
    oauth2:
      client:
        registration:
          gift-certificates-system:
            client-id: gift-certificates-system-id
            client-secret: gift-certificates-system-secret
