server:
  port: 80
  servlet:
    context-path: "/"
spring:
  application:
    name: "client"
  security:
    oauth2:
      client:
        registration:
          gcs_implicit:
            provider: gcs_implicit
            client-id: gift-certificates-system-id
            client-secret: gift-certificates-system-secret
            client-authentication-method: post
            authorization-grant-type: implicit
            redirect-uri: http://localhost:80/login/oauth2/callback/gcs_implicit
            scope: read write gift_certificates_system
            client-name: Gift-certificates System (Implicit Grant)
          gcs_ropc:
            provider: gcs_ropc
            client-id: gift-certificates-system-id
            client-secret: gift-certificates-system-secret
            client-authentication-method: post
            authorization-grant-type: password
            redirect-uri: http://localhost:80/login/oauth2/callback/gcs_ropc
            scope: read write gift_certificates_system
            client-name: Gift-certificates System (Resouce Owner Password Credentials Grant)
        provider:
          gcs_implicit:
            authorization-uri: http://localhost:9999/oauth2/authorize
            token-uri: http://localhost:9999/oauth2/token
            user-info-uri: http://localhost:9999/oauth2/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9999/oauth2/authorize/certs
          gcs_ropc:
            authorization-uri: http://localhost:9999/oauth2/authorize
            token-uri: http://localhost:9999/oauth2/token
            user-info-uri: http://localhost:9999/oauth2/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9999/oauth2/authorize/certs
