server:
  port: 80
  servlet:
    context-path: "/"
    session:
      timeout: "20m"
spring:
  application:
    name: "module_03"
  datasource:
    url: "jdbc:mysql://mysql-aws-prod-instance.eu.s3.eu-west-1.amazonaws.com//gift_certificates_system?logger=com.mysql.cj.log.StandardLogger&profileSQL=true"
    username: "luckyAwsUser"
    password: "rootroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
page:
  default-page-size: 20