server:
  port: 8888
  servlet:
    context-path: "/module_04"
    session:
      timeout: "20m"
spring:
  application:
    name: "module_04"
  datasource:
    url: "jdbc:mysql://localhost:3306/gift_certificates_system?logger=com.mysql.cj.log.StandardLogger&profileSQL=true"
    username: "root"
    password: "rootroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
page:
  default-page-size: 20
security:
  jwt:
    token:
      secret-key: "secret-key-for-jwt-authentication"
      expiration: 900000 # jwt is valid for 15 minutes
